# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - koi-auction

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean install -f koiauction

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
         name: java-app
         path: 'koiauction/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5F595DFBCED847ECBB5900A89488E3CE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_387102A3D172402199D76C78470FE5E2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7C89F749ED4E429F81FD3C769DC1D517 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'koi-auction'
          slot-name: 'Production'
          package: '${{ github.workspace }}/*.jar'  # Đường dẫn đến file JAR  # Adjust path to the JAR file for deployment  # Adjust path to the JAR file for deployment
          
